package cz.muni.fi.pv112;

import com.jogamp.opengl.util.FPSAnimator;
import cz.muni.fi.pv112.controlls.KeyboardController;

import java.awt.*;
import java.awt.image.BufferedImage;
import javax.media.opengl.GLCapabilities;
import javax.media.opengl.GLProfile;
import javax.media.opengl.awt.GLJPanel;
import javax.swing.*;

public class MainWindow extends javax.swing.JFrame {

    private GLProfile profile;
    private GLJPanel canvas;
    private Scene scene;

    public MainWindow(JTextPane jTextPane) {
        initComponents();

        /*
        *   OpenGL profilom sa obmedzujeme
        *   na funkcionalitu dostupnu do verzie OpenGL 3
        */
        profile = GLProfile.get(GLProfile.GL2);

        /*
        *   GLCapabilities obsahuje dalsie vlastnosti
        *   ako antialiasing double buffering atd..
        *
        *   GLJPanel je nase OpenGL okno do ktoreho kreslime
        */
        canvas = new GLJPanel(new GLCapabilities(profile));
        canvas.setLayout(new FlowLayout(FlowLayout.LEFT));
        JLabel jlabel1 = new JLabel("<html>Press ESC to release / track mouse<br>Press F to toggle slow motion</html>");
        canvas.add(jlabel1);









        scene = new Scene();

        KeyboardController keyboard = new KeyboardController();

        scene.setKeyboard(keyboard);
        keyboard.setScene(scene);


        /*
        *   Hlavne okno nasej aplikacie (MainWindow) musi poznat nase OpenGL okno
        *   Preto ho musime umiestnit do hlavneho okna prikazom add()
        */
        this.add(canvas, BorderLayout.CENTER);

        /*
        *   Nase OpenGL okno pouziva na prekreslenie objekt Scene
        *   Aby vedel canvas o objekte scene pridame mu ho do zoznamu listenerov
        *   prikazom addGLEventListener
        */
        canvas.addGLEventListener(scene);
        canvas.addKeyListener(keyboard);
        canvas.addMouseMotionListener(scene);

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Point hotSpot = new Point(0,0);
        BufferedImage cursorImage = new BufferedImage(1, 1, BufferedImage.TRANSLUCENT);
        Cursor invisibleCursor = toolkit.createCustomCursor(cursorImage, hotSpot, "InvisibleCursor");
        scene.setInvisibleCursor(invisibleCursor);
        setCursor(invisibleCursor);

        scene.setWindow(this);


        FPSAnimator a = new FPSAnimator(canvas, 60);
        a.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow(new JTextPane()).setVisible(true);
            }
        });
    }

    public GLJPanel getCanvas() {
        return canvas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}